# ----------------------------------------------------------------------------
# display status message for important variables
# ----------------------------------------------------------------------------
MESSAGE( STATUS )
MESSAGE( STATUS "------------------ General configuration for ${PROJECT_NAME} ${PROJECT_VERSION} ")
MESSAGE( STATUS )
MESSAGE( STATUS "Generator:                  ${CMAKE_GENERATOR}")
MESSAGE( STATUS "Compiler:                   ${CMAKE_CXX_COMPILER_ID}")
IF (${CMAKE_BUILD_TYPE} STREQUAL "Release")
   MESSAGE( STATUS "C++ flags (Release):      ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}")
ELSEIF (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
   MESSAGE( STATUS "C++ flags (Debug):        ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}")
ELSE()
   MESSAGE( FATAL_ERROR "Only Release and Debug build types are allowed")
ENDIF ()
MESSAGE( STATUS )
MESSAGE( STATUS "USE_CLANG =                 ${USE_CLANG}" )
MESSAGE( STATUS "BUILD_SHARED_LIBS =         ${BUILD_SHARED_LIBS}" )
MESSAGE( STATUS "BUILD_TESTS =               ${BUILD_TESTS}" )
MESSAGE( STATUS "BUILD_UTILS =               ${BUILD_UTILS}" )
MESSAGE( STATUS "WARNINGS_ANSI_ISO =         ${WARNINGS_ANSI_ISO}" )
MESSAGE( STATUS "WARNINGS_ARE_ERRORS =       ${WARNINGS_ARE_ERRORS}" )
MESSAGE( STATUS "CMAKE_SYSTEM_PROCESSOR =    ${CMAKE_SYSTEM_PROCESSOR}" )
MESSAGE( STATUS "ENABLE_COVERAGE =           ${ENABLE_COVERAGE}" )
MESSAGE( STATUS "ENABLE_COVERAGE_XML =       ${ENABLE_COVERAGE_XML}")
MESSAGE( STATUS "CMAKE_INSTALL_PREFIX =      ${CMAKE_INSTALL_PREFIX}" )
MESSAGE( STATUS )
MESSAGE( STATUS "------------------- Documentation  ----------------------" )
MESSAGE( STATUS )
MESSAGE( STATUS "INSTALL_DOC =               ${INSTALL_DOC}" )
MESSAGE( STATUS "DOXY_COVERAGE =             ${DOXY_COVERAGE}" )
MESSAGE( STATUS "USE_LATEX =                 ${USE_LATEX}" )
MESSAGE( STATUS "USE_DOT =                   ${USE_DOT}" )
MESSAGE( STATUS "USE_CHM =                   ${USE_CHM}" )
MESSAGE( STATUS "USE_MATHJAX =               ${USE_MATHJAX}" )
MESSAGE( STATUS )
MESSAGE( STATUS "Change a value with: cmake -D<Variable>=<Value>" )
MESSAGE( STATUS )
